# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fcb1924abc340e918e358341be4b0ff06fec1167da6df8acf0ac60fbcacacbca546895c18f1b45ffdbd20c3de099d6599d30669fbd787aaf4648df614571b8e

test:
  secret_key_base: 946aa80e56c2138979dab16538e82b675a5c88bac6c259f1f82faf5f748d43de4502cd49df7b3de9de8e38cda4f9a9d23b7ecfc41b6341c9013b97854021caeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
